const photosTwo = [
  [
    { id: 1, img: new URL("../assets/img/photos/1.jpg", import.meta.url) },
    { id: 3, img: new URL("../assets/img/photos/3.jpg", import.meta.url) },
    { id: 5, img: new URL("../assets/img/photos/5.jpg", import.meta.url) },
    { id: 7, img: new URL("../assets/img/photos/7.jpg", import.meta.url) },
    { id: 9, img: new URL("../assets/img/photos/9.jpg", import.meta.url) },
    { id: 11, img: new URL("../assets/img/photos/11.jpg", import.meta.url) },
    { id: 13, img: new URL("../assets/img/photos/13.jpg", import.meta.url) },
    { id: 15, img: new URL("../assets/img/photos/15.jpg", import.meta.url) },
    { id: 17, img: new URL("../assets/img/photos/17.jpg", import.meta.url) },
    { id: 19, img: new URL("../assets/img/photos/19.jpg", import.meta.url) },
    { id: 21, img: new URL("../assets/img/photos/21.jpg", import.meta.url) },
    { id: 23, img: new URL("../assets/img/photos/23.jpg", import.meta.url) },
    { id: 25, img: new URL("../assets/img/photos/25.jpg", import.meta.url) },
    { id: 27, img: new URL("../assets/img/photos/27.jpg", import.meta.url) },
    { id: 29, img: new URL("../assets/img/photos/29.jpg", import.meta.url) },
    { id: 31, img: new URL("../assets/img/photos/31.jpg", import.meta.url) },
    { id: 33, img: new URL("../assets/img/photos/33.jpg", import.meta.url) },
    { id: 35, img: new URL("../assets/img/photos/35.jpg", import.meta.url) },
    { id: 37, img: new URL("../assets/img/photos/37.jpg", import.meta.url) },
    { id: 39, img: new URL("../assets/img/photos/39.jpg", import.meta.url) },
  ],
  [
    { id: 2, img: new URL("../assets/img/photos/2.jpg", import.meta.url) },
    { id: 4, img: new URL("../assets/img/photos/4.jpg", import.meta.url) },
    { id: 6, img: new URL("../assets/img/photos/6.jpg", import.meta.url) },
    { id: 8, img: new URL("../assets/img/photos/8.jpg", import.meta.url) },
    { id: 10, img: new URL("../assets/img/photos/10.jpg", import.meta.url) },
    { id: 12, img: new URL("../assets/img/photos/12.jpg", import.meta.url) },
    { id: 14, img: new URL("../assets/img/photos/14.jpg", import.meta.url) },
    { id: 16, img: new URL("../assets/img/photos/16.jpg", import.meta.url) },
    { id: 18, img: new URL("../assets/img/photos/18.jpg", import.meta.url) },
    { id: 20, img: new URL("../assets/img/photos/20.jpg", import.meta.url) },
    { id: 22, img: new URL("../assets/img/photos/22.jpg", import.meta.url) },
    { id: 24, img: new URL("../assets/img/photos/24.jpg", import.meta.url) },
    { id: 26, img: new URL("../assets/img/photos/26.jpg", import.meta.url) },
    { id: 28, img: new URL("../assets/img/photos/28.jpg", import.meta.url) },
    { id: 30, img: new URL("../assets/img/photos/30.jpg", import.meta.url) },
    { id: 32, img: new URL("../assets/img/photos/32.jpg", import.meta.url) },
    { id: 34, img: new URL("../assets/img/photos/34.jpg", import.meta.url) },
    { id: 36, img: new URL("../assets/img/photos/36.jpg", import.meta.url) },
    { id: 38, img: new URL("../assets/img/photos/38.jpg", import.meta.url) },
    { id: 40, img: new URL("../assets/img/photos/40.jpg", import.meta.url) }
  ]
];

export default photosTwo;